version: '3.7'
services:
  web:
    image: node:lts-alpine
    command: sleep infinity
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - "8080:8080"
      - "8033:8033"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: test
    volumes:
      - ../mongo:/data/db
    ports:
      - "27017:27017"